package fr.Brunoy.gestion_tournois_FFTT.common.exception;

public enum ErrorCode {

    // -------- REGION --------
    REGION_CODE_REQUIRED,
    REGION_NAME_REQUIRED,

    // -------- DEPARTEMENT --------
    DEPARTEMENT_CODE_REQUIRED,
    DEPARTEMENT_NAME_REQUIRED,
    DEPARTEMENT_REGION_REQUIRED,

    // -------- CLUB --------
    CLUB_NUMBER_REQUIRED,
    CLUB_NAME_REQUIRED,
    CLUB_CITY_REQUIRED,
    CLUB_DEPARTEMENT_REQUIRED,

    // -------- OFFICIAL / QUALIFICATION --------
    OFFICIAL_ROLE_REQUIRED,
    OFFICIAL_GRADE_REQUIRED,
    OFFICIAL_INCONSISTENT_GRADE,

    // -------- PLAYER --------
    PLAYER_REQUIRED,
    PLAYER_LICENSE_REQUIRED,
    PLAYER_FIRST_NAME_REQUIRED,
    PLAYER_LAST_NAME_REQUIRED,
    PLAYER_GENDER_REQUIRED,
    PLAYER_NATIONALITY_REQUIRED,
    PLAYER_CLUB_REQUIRED,
    PLAYER_AGE_CATEGORY_REQUIRED,
    PLAYER_LICENSE_TYPE_REQUIRED,
    PLAYER_MEDICAL_CERT_REQUIRED,
    PLAYER_POINTS_NEGATIVE,
    PLAYER_QUALIFICATION_REQUIRED,

    // -------- TABLEAU (DEFINITION) --------
    TABLEAU_CODE_REQUIRED,
    TABLEAU_DESIGNATION_REQUIRED,
    TABLEAU_DATE_REQUIRED,
    TABLEAU_GENDER_POLICY_REQUIRED,
    TABLEAU_POINTS_RULE_TYPE_REQUIRED,

    TABLEAU_MIN_POINTS_REQUIRED,
    TABLEAU_MAX_POINTS_REQUIRED,
    TABLEAU_MIN_POINTS_NEGATIVE,
    TABLEAU_MAX_POINTS_NEGATIVE,
    TABLEAU_MIN_GREATER_THAN_MAX,
    TABLEAU_POINTS_RULE_INCONSISTENT,

    TABLEAU_FEE_REQUIRED,
    TABLEAU_FEE_NEGATIVE,

    TABLEAU_CHECKIN_TIME_REQUIRED,
    TABLEAU_START_TIME_REQUIRED,
    TABLEAU_CHECKIN_AFTER_START,

    TABLEAU_PRIZE_REQUIRED,
    TABLEAU_PRIZE_NEGATIVE,

    // -------- TABLEAU (CAPACITE / INSCRIPTION) --------
    TABLEAU_MAX_PLAYERS_INVALID,
    TABLEAU_FULL,

    // -------- TOURNAMENT --------
    TOURNAMENT_REQUIRED,
    TOURNAMENT_NAME_REQUIRED,
    TOURNAMENT_ORGANIZING_CLUB_REQUIRED,
    TOURNAMENT_LEVEL_REQUIRED,
    TOURNAMENT_RANKING_PHASE_REQUIRED,
    TOURNAMENT_DAYS_REQUIRED,

    TOURNAMENT_TABLEAU_REQUIRED,
    TOURNAMENT_TABLEAU_CODE_DUPLICATE,
    TOURNAMENT_TABLEAU_DATE_NOT_IN_TOURNAMENT_DAYS,
    TOURNAMENT_FEMALE_EXTRA_RULE_REQUIRED,
    TOURNAMENT_FEMALE_EXTRA_TABLEAU_CODE_REQUIRED,

    // -------- TOURNAMENT (REGLES D’INSCRIPTION) --------
    TOURNAMENT_REGISTRATION_POLICY_REQUIRED,
    TOURNAMENT_MAX_TABLEAUX_PER_DAY_INVALID,
    TOURNAMENT_MAX_TOTAL_TABLEAUX_INVALID,
    TOURNAMENT_MAX_TOTAL_TABLEAUX_TOO_LOW,

    // -------- REGISTRATION --------
    REGISTRATION_REQUIRED,
    REGISTRATION_INVALID,
    REGISTRATION_TABLEAU_NOT_FOUND,
    REGISTRATION_ALREADY_REGISTERED,
    REGISTRATION_NOT_ELIGIBLE,

    // -------- REGISTRATION (MULTI) --------
    REGISTRATION_MAX_TOTAL_TABLEAUX_EXCEEDED,
    REGISTRATION_MAX_TABLEAUX_PER_DAY_EXCEEDED,
    REGISTRATION_TOO_MANY_FEMALE_ONLY_TABLEAUX_PER_DAY,
    REGISTRATION_MEDICAL_CERT_INVALID,

    REGISTRATION_PAYMENT_MODE_REQUIRED,
    REGISTRATION_STATUS_REQUIRED,
    REGISTRATION_BATCH_ID_REQUIRED,
    REGISTRATION_BATCH_NOT_FOUND,
    REGISTRATION_RESERVATION_EXPIRED,

    REGISTRATION_PLAYER_NOT_IN_DEPARTEMENT,
    REGISTRATION_PLAYER_NOT_IN_REGION,
    REGISTRATION_LEVEL_INTERNATIONAL_NOT_SUPPORTED,

    TOURNAMENT_HOMOLOGATION_REQUIRED_FOR_PUBLICATION,

    TOURNAMENT_ORGANIZER_CONTACT_REQUIRED,
    TOURNAMENT_VENUE_REQUIRED,
    TOURNAMENT_TABLE_COUNT_INVALID,

    TOURNAMENT_PLAYING_AREA_REQUIRED,
    TOURNAMENT_PLAYING_AREA_INCOMPATIBLE_LEVEL,
    TOURNAMENT_PLAYING_AREA_CUSTOM_INFO_REQUIRED,
    TOURNAMENT_PLAYING_AREA_DIMENSIONS_INCOMPLETE,
    TOURNAMENT_PLAYING_AREA_DIMENSIONS_INVALID,

    TOURNAMENT_BALL_INFO_REQUIRED,

    TOURNAMENT_REGISTRATION_DEADLINE_REQUIRED,
    TOURNAMENT_CHECKIN_DEADLINE_REQUIRED,
    TOURNAMENT_FIRST_MATCH_START_REQUIRED,
    TOURNAMENT_TIMELINE_INCONSISTENT,

    TOURNAMENT_EXPECTED_END_TIME_REQUIRED,
    TOURNAMENT_REGULATION_INFO_REQUIRED,
}
